server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;

       # location /app-authors/ {
       #     proxy_pass http://app-authors/;
       # }

        #location /app-books/ {
        #    proxy_pass http://app-books/;
        #}
}