# -- Crear la imagen
# docker build -f src/main/docker/Dockerfile.jvm -t app-customers .
# docker build -f src/main/docker/Dockerfile.jvm -t xd456/app-customers .
# docker login
# docker push xd456/app-customers
# docker logout
#

FROM docker.io/eclipse-temurin:25.0.3_9-jre-alpine

ENV LANGUAGE='en_US:en'

RUN mkdir /app
WORKDIR /app

# Si importa el orden de las capas lib debe ir primero siempre
COPY build/libs/app-customers.jar app.jar

CMD ["java", "-jar", "app.jar"]