CREATE TABLE IF NOT EXISTS customers
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20),
    address VARCHAR(255),
    created_at TIMESTAMP,
    version INTEGER,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

INSERT INTO customers (first_name, last_name, email, phone, address, created_at) VALUES ('Joffre', 'Perez', 'joffred.@hotmail.com', '12345678', 'Quito', CURRENT_TIMESTAMP);
INSERT INTO customers (first_name, last_name, email, phone, address, created_at) VALUES ('Pepe', 'Gomez', 'pepe.@hotmail.com', '87654321', 'Guayaquil', CURRENT_TIMESTAMP);
INSERT INTO customers (first_name, last_name, email, phone, address, created_at) VALUES ('Juan', 'Perez', 'juan.@hotmail.com', '1111111', 'Cuenca', CURRENT_TIMESTAMP);
INSERT INTO customers (first_name, last_name, email, phone, address, created_at) VALUES ('Maria', 'Lopez', 'maria.@hotmail.com', '2222222', 'Loja', CURRENT_TIMESTAMP);
INSERT INTO customers (first_name, last_name, email, phone, address, created_at) VALUES ('Ana', 'Garcia', 'ana.@hotmail.com', '3333333', 'Manta', CURRENT_TIMESTAMP);