CREATE TABLE authors
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    version INTEGER,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

INSERT INTO authors (name) VALUES ('J.K. Rowling');
INSERT INTO authors (name) VALUES ('George R.R. Martin');
INSERT INTO authors (name) VALUES ('J.R.R. Tolkien');
